writing: neoaramaic

data:
  org: CambridgeSemiticsLab
  repo: nena_tf
  rel: tf
  version: alpha
  docUrl: «ghUrl»/«data.org»/«data.repo»/blob/master/docs/features.md

corpus:
  text: North Eastern Neo Aramaic
  url: "https://nena.ames.cam.ac.uk"
  tip: North-Eastern Neo-Aramaic Data Project website

author1:
  text: Cody Kingham
  role: corpus developer
  url: "https://www.linkedin.com/in/cody-kingham-1135018a"
  tip: corpus developer

author2:
  text: Geoffrey Khan
  role: lead researcher
  url: "https://www.ames.cam.ac.uk/people/professor-geoffrey-khan"
  tip: lead researcher
